version: '2'
services:
  node:
    build: ./node
    volumes:
     - ../:/usr/src/app:z
    expose:
     - 80
    environment:
     - PORT=80
     - NODE_ENV=production
    container_name: etic-node
  nginx:
    build: ./nginx
    ports:
     - 80:80
     - 443:443
    volumes:
     - ./nginx/config:/usr/share/nginx/config:z
     - ~/ssl:/usr/share/nginx/ssl:z
     - ../static:/usr/share/nginx/html/static:z
    container_name: etic-nginx
    depends_on:
     - node
